Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/06/2023
Var
   raio, area: real

Inicio
   escreva("Digite o valor do raio do círculo: ")
   leia(raio)

   area <- 3.14159 * (Exp(raio,2))

   escreval("Área= ", area:3:3)



Fimalgoritmo