Algoritmo "Exercicio3"

Var
   larg: inteiro
   comp: inteiro
   metro_quad: inteiro
   area, preco: real


Inicio

   area <- 300.00
   preco <- 60000.00
   area <- larg * comp

   escreva("Digite a largura do terreno: ")
   leia(larg)
   escreva("Digite o comprimento do terreno: ")
   leia(comp)
   escreva("Digite o valor do metro quadrado: ")
   leia(metro_quad)
   escreval("Area do terreno = ", )




Fimalgoritmo